language: python
sudo: required
python:
  - "2.7"
  - "3.6"
before_install:
  - sudo apt-get -y update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda install -c biocore mafft
  - conda install -c bioconda fasttree
  - conda install -c bioconda iqtree
  - conda install -c bioconda raxml
  - conda install -c bioconda vcftools
  - source activate test-environment
install:
  - if [ $TRAVIS_PYTHON_VERSION = "2.7" ]; then pip install -r requirements.txt; fi
  - if [ $TRAVIS_PYTHON_VERSION = "3.6" ]; then pip3 install --process-dependency-links -e .[dev]; fi
script:
  - if [ $TRAVIS_PYTHON_VERSION = "2.7" ]; then pytest; fi
  - if [ $TRAVIS_PYTHON_VERSION = "3.6" ]; then (cd tests/builds/zika/; snakemake); fi
  - if [ $TRAVIS_PYTHON_VERSION = "3.6" ]; then (cd tests/builds/tb/; snakemake); fi
